---
# tasks file for lvmd
- name: Create a volume groups for lvmd
  lvg: 
    vg: "{{ item.key | lower }}"
    pvs: "{{ item.value.pvs | join(',') }}"
  with_dict: "{{ topolvm_volume_groups }}"
  when: topolvm_volume_groups is defined

- name: check if lvmd is already present
  stat:
    path: /usr/local/bin/lvmd
  register: topolvm_binary

- name: get installed version of
  shell: /usr/local/bin/lvmd --version | awk '{print $3}'
  register: topolvm_installed_version
  when: topolvm_binary.stat.exists

- name: take lvmd service down and delete binary
  block:
    - shell: /usr/bin/systemctl list-units lvmd.service
      register: topolvm_service_stat
      #ignore_errors: yes

    - systemd:
        name: lvmd.service
        state: stopped
      when: topolvm_service_stat is succeeded

    - file:
        path: /usr/local/bin/lvmd
        state: absent
  when: 
    - topolvm_binary.stat.exists
    - topolvm_installed_version.stdout != topolvm_version

- name: build combined version
  set_fact:
    topolvm_br_full_version: "{{ topolvm_version }}{{ topolvm_backup_restore_revision }}"

- debug:
    var: topolvm_installed_version.stdout

- debug:
    var: topolvm_br_full_version

- name: download and unarchive lvmd
  unarchive:
    src: "{{ topolvm_github_repo }}/releases/download/v{{ topolvm_version }}/lvmd-{{ topolvm_br_full_version }}.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
  environment: "{{ environment_variables | default({}) }}"
  when: 
    - topolvm_installed_version is defined
    - topolvm_installed_version.stdout | default('') != topolvm_br_full_version

- name: Place systemd unit file
  template:
    src: lvmd.service.j2
    dest: /usr/lib/systemd/system/lvmd.service
  register: topolvm_unit_file

- name: ensure dir is present
  file:
    state: directory
    path: /etc/topolvm

- name: Template lvmd config file
  template:
    src: lvmd.yaml
    dest: /etc/topolvm/lvmd.yaml
    mode: 0644
  register: topolvm_conf_file

- name: Copy backup and restore scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  loop:
    - { src: "backup.sh", dest: "/usr/local/bin/topolvm-backup.sh"}
    - { src: "restore.sh", dest: "/usr/local/bin/topolvm-restore.sh"}

- name: Enable and start lvmd service
  systemd:
    name: lvmd
    enabled: yes
    state: started
    daemon_reload: yes
  
- name: Enable and restart lvmd service
  systemd:
    name: lvmd
    enabled: yes
    state: restarted
    daemon_reload: yes
  when: topolvm_unit_file.changed or topolvm_conf_file.changed