---
# tasks file for lvmd

# Installation (default)
- include: 'requirements.yml'
- include: 'cert_manager.yml'
  when: topolvm_cert_manager_manage == true
- include: 'lvmd.yml'
- include: 'k8s_manifests.yml'
- include: 'verify_deployment.yml'
  when: topolvm_uninstall | default(false) == false

## Uninstallation
- include: 'k8s_manifests_uninstall.yml'
  when: topolvm_uninstall | default(false) == true
- include: 'topolvm_uninstall.yml'
  when: topolvm_uninstall | default(false) == true
- include: 'cert_manager_uninstall.yml'
  when: 
    - topolvm_cert_manager_manage == true
    - topolvm_uninstall | default(false) == true