---
- block:
    - name: install epel-release
      package:
        name: epel-release
        update_cache: yes
      environment: "{{ environment_variables | default({}) }}"
      when: ansible_os_family == "RedHat"

    - name: install pip
      package:
        name: 
          - python3-pip
          - python-pip
        update_cache: yes
      environment: "{{ environment_variables | default({}) }}"

    - name: install python reqs for openshift lib
      pip:
        name: 
          #- setuptools>=44.1.0
          - setuptools
          - wheel
        #executable: pip2.7
        executable: pip3
      environment: "{{ environment_variables | default({}) }}"

    - name: install python openshift lib
      pip:
        name: openshift
        #executable: pip2.7
        executable: pip3
      environment: "{{ environment_variables | default({}) }}"
      
  when: "ansible_hostname == groups['kube-master'][0]"