galaxy_info:
  author: Lucas Zanella
  description: |
    This roles is intened to automate rollout and update topolvm (https://github.com/cybozu-go/topolvm) on a existing k8s cluster.
    
    Requirements:
      - cert manager must be enabled
      - clean block devices or partitions available to be used as "pv" for volume group creation

    TODO:
      - Possibility to run deployment without cert-manager

  company: your company (optional)

  license: Apache-2.0

  min_ansible_version: 2.7

  platforms:
  - name: Centos
    versions:
    - 7
    - 8
  - name: Debian
    versions:
    - 10

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
  