---
- name: Get the kubeadm version
  command: "{{ bin_dir }}/kubeadm version -o short"
  register: kubeadm_output
  changed_when: false

- name: Set kubeadm api version to v1beta2
  set_fact:
    kubeadmConfig_api_version: v1beta2

#############################################
###### Sulzer Start #########################
#############################################
## It's important to not set topolvm (lvmd) config when 
## initial rollout happens, otherwise kube-scheduler would 
## fail because of missing topolvm dependencies that would 
## come with role 'lvmd'
- name: lvmd | check if kubeadm-config.yaml is there
  stat:
    path: /etc/kubernetes/kubeadm-config.yaml
  register: topolvm_kubeadm_config

- name: lvmd | check if there is already topolvm deployed
  shell: "grep -i .*topolvm.* /etc/kubernetes/kubeadm-config.yaml | wc -l"
  register: topolvm_topolvm_in_found
  when: topolvm_kubeadm_config.stat.exists

- fail:
    msg: "var \"topolvm_kube_kubeadm_scheduler_extra_args\" not defined"
  when: 
    - groups['lvmd'] is defined
    - not (topolvm_kube_kubeadm_scheduler_extra_args is defined)

- fail:
    msg: "var \"topolvm_scheduler_extra_volumes\" not defined"
  when: 
    - groups['lvmd'] is defined
    - not (topolvm_scheduler_extra_volumes is defined)

- debug:
    msg: "{{ item }}"
  loop:
    - "{{ kube_kubeadm_scheduler_extra_args_fact | default('') }}"
    - "{{ topolvm_topolvm_in_found.stdout | default('') }}"

- name: lvmd | build_topolvm_facts
  set_fact:
    kube_kubeadm_scheduler_extra_args_fact: "{{ topolvm_kube_kubeadm_scheduler_extra_args }}"
    scheduler_extra_volumes_fact: "{{ topolvm_scheduler_extra_volumes }}"
  when: 
    - topolvm_kubeadm_config.stat.exists
    - topolvm_topolvm_in_found.stdout | default('') != '0'

- debug:
    msg: "{{ item }}"
  loop:
    - "{{ kube_kubeadm_scheduler_extra_args_fact | default('') }}"
    - "{{ topolvm_topolvm_in_found.stdout | default('') }}"

#############################################
###### Sulzer Stop ##########################
#############################################

#############################################
###### Sulzer Start #########################
#############################################
## It's important to not set topolvm (lvmd) config when 
## initial rollout happens, otherwise kube-scheduler would 
## fail because of missing topolvm dependencies that would 
## come with role 'lvmd'
- name: lvmd | check if kubeadm-config.yaml is there
  stat:
    path: /etc/kubernetes/kubeadm-config.yaml
  register: topolvm_kubeadm_config

- name: lvmd | check if there is already topolvm deployed
  shell: "grep -i .*topolvm.* /etc/kubernetes/kubeadm-config.yaml | wc -l"
  register: topolvm_topolvm_in_found
  when: topolvm_kubeadm_config.stat.exists

- fail:
    msg: "var \"topolvm_kube_kubeadm_scheduler_extra_args\" not defined"
  when: 
    - groups['lvmd'] is defined
    - not (topolvm_kube_kubeadm_scheduler_extra_args is defined)

- fail:
    msg: "var \"topolvm_scheduler_extra_volumes\" not defined"
  when: 
    - groups['lvmd'] is defined
    - not (topolvm_scheduler_extra_volumes is defined)

- debug:
    msg: "{{ item }}"
  loop:
    - "{{ kube_kubeadm_scheduler_extra_args_fact | default('') }}"
    - "{{ topolvm_topolvm_in_found.stdout | default('') }}"

- name: lvmd | build_topolvm_facts
  set_fact:
    kube_kubeadm_scheduler_extra_args_fact: "{{ topolvm_kube_kubeadm_scheduler_extra_args }}"
    scheduler_extra_volumes_fact: "{{ topolvm_scheduler_extra_volumes }}"
  when: 
    - topolvm_kubeadm_config.stat.exists
    - topolvm_topolvm_in_found.stdout | default('') != '0'

- debug:
    msg: "{{ item }}"
  loop:
    - "{{ kube_kubeadm_scheduler_extra_args_fact | default('') }}"
    - "{{ topolvm_topolvm_in_found.stdout | default('') }}"

#############################################
###### Sulzer Stop ##########################
#############################################

- name: kubeadm | Create kubeadm config
  template:
    src: "kubeadm-config.{{ kubeadmConfig_api_version }}.yaml.j2"
    dest: "{{ kube_config_dir }}/kubeadm-config.yaml"
    mode: 0640

#############################################
###### Sulzer Start #########################
#############################################

- name: lvmd | build_topolvm_facts
  set_fact:
    kube_kubeadm_scheduler_extra_args_fact: "{{ topolvm_kube_kubeadm_scheduler_extra_args }}"
    scheduler_extra_volumes_fact: "{{ topolvm_scheduler_extra_volumes }}"
  when: 
    - topolvm_kube_kubeadm_scheduler_extra_args is defined
    - topolvm_scheduler_extra_volumes is defined

- name: lvmd | build kubeadm config for lvmd rollout
  template:
    src: "kubeadm-config.{{ kubeadmConfig_api_version }}.yaml.j2"
    dest: "{{ kube_config_dir }}/kubeadm-config-topolvm.yaml"
    mode: 0640

# - name: lvmd | unset build_topolvm_facts
#   set_fact:
#     kube_kubeadm_scheduler_extra_args_fact:
#     scheduler_extra_volumes_fact:

#############################################
###### Sulzer Stop ##########################
#############################################