---
- name: Set fact for Debian
  block:
    - set_fact:
        misc_packages: "{{ misc.packages.debian }}"
    - set_fact:
        kernel_target: "{{ kernel.version.debian }}"
      when: not (kernel_target is defined)
  when: ansible_os_family == "Debian"

- name: Set fact for RedHat
  block:
    - set_fact:
        misc_packages: "{{ misc.packages.redhat }}"
    - set_fact:
        kernel_target: "{{ kernel.version.redhat }}"
      when: not (kernel_target is defined)
  when: ansible_os_family == "RedHat"