---
- name: gets the kubeadm version
  command: "{{ bin_dir }}/kubeadm version -o short"
  register: kubeadm_output

- name: sets kubeadm api version to v1beta2
  set_fact:
    kubeadmConfig_api_version: v1beta2
  when: kubeadm_output.stdout is version('v1.15.0', '>=')

#############################################
###### Sulzer Start #########################
#############################################
## It's important to not set topolvm (lvmd) config when 
## initial rollout happens, otherwise kube-scheduler would 
## fail because of missing topolvm dependencies that would 
## come with role 'lvmd'
- name: lvmd | check if kubeadm-config.yaml is there
  stat:
    path: /etc/kubernetes/kubeadm-config.yaml
  register: lvmd_kubeadm_config

- name: lvmd | check if there is already topolvm deployed
  shell: "grep -i .*topolvm.* /etc/kubernetes/kubeadm-config.yaml | wc -l"
  register: lvmd_topolvm_in_found
  when: lvmd_kubeadm_config.stat.exists

- fail:
    msg: "var \"lvmd_kube_kubeadm_scheduler_extra_args\" not defined"
  when: 
    - group['lvmd'] is defined
    - not (lvmd_kube_kubeadm_scheduler_extra_args is defined)

- fail:
    msg: "var \"lvmd_scheduler_extra_volumes\" not defined"
  when: 
    - group['lvmd'] is defined
    - not (lvmd_scheduler_extra_volumes is defined)

- name: lvmd | build_topolvm_facts
  set_fact:
    kube_kubeadm_scheduler_extra_args_fact: "{{ lvmd_kube_kubeadm_scheduler_extra_args }}"
    scheduler_extra_volumes_fact: "{{ lvmd_scheduler_extra_volumes }}"
  when: 
    - lvmd_topolvm_in_found.stdout | default('') != '0'
    - lvmd_kube_kubeadm_scheduler_extra_args is defined
    - lvmd_scheduler_extra_volumes is defined

#############################################
###### Sulzer Stop ##########################
#############################################

- name: kubeadm | Create kubeadm config
  template:
    src: "kubeadm-config.{{ kubeadmConfig_api_version }}.yaml.j2"
    dest: "{{ kube_config_dir }}/kubeadm-config.yaml"
    mode: 0640

#############################################
###### Sulzer Start #########################
#############################################

- name: lvmd | build_topolvm_facts
  set_fact:
    kube_kubeadm_scheduler_extra_args_fact: "{{ lvmd_kube_kubeadm_scheduler_extra_args }}"
    scheduler_extra_volumes_fact: "{{ lvmd_scheduler_extra_volumes }}"
  when: 
    - lvmd_kube_kubeadm_scheduler_extra_args is defined
    - lvmd_scheduler_extra_volumes is defined

- name: lvmd | build kubeadm config for lvmd rollout
  template:
    src: "kubeadm-config.{{ kubeadmConfig_api_version }}.yaml.j2"
    dest: "{{ kube_config_dir }}/kubeadm-config-topolvm.yaml"
    mode: 0640

- name: lvmd | unset build_topolvm_facts
  set_fact:
    kube_kubeadm_scheduler_extra_args_fact:
    scheduler_extra_volumes_fact:
#############################################
###### Sulzer Stop ##########################
#############################################